<?php
 /* Author Shashi */ 
	include_once (dirname(__FILE__).'/connect.php');
	$retVal="";	

$retVal.='<loadtypes>';
$retVal.='<none>None</none>';
$retVal.='<fiscalstart>01-January</fiscalstart>';
$retVal.='<fiscalstart>01-Baishakh</fiscalstart>';
$retVal.='<fiscalstart>01-Shrawan</fiscalstart>';
$retVal.='<fiscalstart>06-April</fiscalstart>';
$retVal.='<sitetype>INF_Nepal</sitetype>';
$retVal.='<sitetype>INF_Worldwide</sitetype>';
$retVal.='<sitetype>Patient</sitetype>';
$retVal.='<movementfixeddates>Yes</movementfixeddates>';
$retVal.='<movementfixeddates>No</movementfixeddates>';
//$retVal.='<movementreason>Select..</movementreason>';
//$retVal.='<movementreason>Holiday</movementreason>';
//$retVal.='<movementreason>Home Leave</movementreason>';
//$retVal.='<movementreason>Training</movementreason>';
//$retVal.='<movementreason>Work</movementreason>';
//$retVal.='<movementreason>Other</movementreason>';
$retVal.='<insuranceclass>None</insuranceclass>';
$retVal.='<insuranceclass>I</insuranceclass>';
$retVal.='<insuranceclass>II</insuranceclass>';
$retVal.='<insuranceclass>III</insuranceclass>';
$retVal.='<insuranceclass>IV</insuranceclass>';
$retVal.='<staffstatus>None</staffstatus>';
$retVal.='<staffstatus>Staff</staffstatus>';
$retVal.='<staffstatus>Member</staffstatus>';
$retVal.='<staffstatus>Associate</staffstatus>';
$retVal.='<staffstatus>Applicant</staffstatus>';
$retVal.='<staffstatus>STV</staffstatus>';
$retVal.='<staffstatus>Intern</staffstatus>';
$retVal.='<staffstatus>Elective</staffstatus>';
$retVal.='<staffstatus>Visitor</staffstatus>';
$retVal.='<postjobreviewer>No</postjobreviewer>';
$retVal.='<postjobreviewer>Yes</postjobreviewer>';
$retVal.='<postmedicalreviewer>No</postmedicalreviewer>';
$retVal.='<postmedicalreviewer>Yes</postmedicalreviewer>';
$retVal.='<postpersonnelreviewer>No</postpersonnelreviewer>';
$retVal.='<postpersonnelreviewer>Yes</postpersonnelreviewer>';
$retVal.='<postprovisional>No</postprovisional>';
$retVal.='<postprovisional>Yes</postprovisional>';
$retVal.='<postactive>No</postactive>';
$retVal.='<postactive>Yes</postactive>';
$retVal.='<posthour>Full-time</posthour>';
$retVal.='<posthour>Part-time</posthour>';
$retVal.='<poststatus>Contract</poststatus>';
$retVal.='<poststatus>Permanent</poststatus>';
$retVal.='<poststatus>Temporary</poststatus>';
$retVal.='<posttype>Admin</posttype>';
$retVal.='<posttype>Admin/Tech</posttype>';
$retVal.='<posttype>Internal</posttype>';
$retVal.='<posttype>Medical</posttype>';
$retVal.='<posttype>Official</posttype>';
$retVal.='<posttype>Tech</posttype>';
$retVal.='<postholder>No</postholder>';
$retVal.='<postholder>Yes</postholder>';
$retVal.='<type>Select..</type>';
$retVal.='<type>Personal</type>';
$retVal.='<type>Family</type>';
$retVal.='<type>Office</type>';
$retVal.='<type>Contact</type>';
$retVal.='<type>Permanent</type>';
$retVal.='<title>Select..</title>';
$retVal.='<title>Mr</title>';
$retVal.='<title>Mrs</title>';
$retVal.='<title>Miss</title>';
$retVal.='<title>Dr</title>';
$retVal.='<leaveReplacement>No</leaveReplacement>';
$retVal.='<leaveReplacement>Yes</leaveReplacement>';
$retVal.='<specialcontract>No</specialcontract>';
$retVal.='<specialcontract>Yes</specialcontract>';
$retVal.='<gender>Select..</gender>';
$retVal.='<gender>Male</gender>';
$retVal.='<gender>Female</gender>';
$retVal.='<bloodgroup>None</bloodgroup>';
$retVal.='<bloodgroup>A+</bloodgroup>';
$retVal.='<bloodgroup>A-</bloodgroup>';
$retVal.='<bloodgroup>B+</bloodgroup>';
$retVal.='<bloodgroup>B-</bloodgroup>';
$retVal.='<bloodgroup>AB+</bloodgroup>';
$retVal.='<bloodgroup>AB-</bloodgroup>';
$retVal.='<bloodgroup>O+</bloodgroup>';
$retVal.='<bloodgroup>O-</bloodgroup>';
$retVal.='<relation>Select..</relation>';
$retVal.='<relation>Aunt</relation>';
$retVal.='<relation>Brother</relation>';
$retVal.='<relation>Brother-in-law</relation>';
$retVal.='<relation>Child</relation>';
$retVal.='<relation>Child-in-law</relation>';
$retVal.='<relation>Cousin</relation>';
$retVal.='<relation>Daughter</relation>';
$retVal.='<relation>Daughter-in-law</relation>';
$retVal.='<relation>Father</relation>';
$retVal.='<relation>Father-in-law</relation>';
$retVal.='<relation>Grandchild</relation>';
$retVal.='<relation>Granddaughter</relation>';
$retVal.='<relation>Grandfather</relation>';
$retVal.='<relation>Grandmother</relation>';
$retVal.='<relation>Grandparent</relation>';
$retVal.='<relation>Grandson</relation>';
$retVal.='<relation>Husband</relation>';
$retVal.='<relation>Mother</relation>';
$retVal.='<relation>Mother-in-law</relation>';
$retVal.='<relation>Nephew</relation>';
$retVal.='<relation>Niece</relation>';
$retVal.='<relation>Parent</relation>';
$retVal.='<relation>Parent-in-law</relation>';
$retVal.='<relation>Parent-sibling</relation>';
$retVal.='<relation>Sibling</relation>';
$retVal.='<relation>Sibling-child</relation>';
$retVal.='<relation>Sibling-in-law</relation>';
$retVal.='<relation>Sister</relation>';
$retVal.='<relation>Sister-in-law</relation>';
$retVal.='<relation>Son</relation>';
$retVal.='<relation>Son-in-law</relation>';
$retVal.='<relation>Spouse</relation>';
$retVal.='<relation>Uncle</relation>';
$retVal.='<relation>Wife</relation>';
$retVal.='<relation>Other</relation>';

$retVal.='<malerelation>Select..</malerelation>';
$retVal.='<malerelation>Brother</malerelation>';
$retVal.='<malerelation>Brother-in-law</malerelation>';
$retVal.='<malerelation>Cousin</malerelation>';
$retVal.='<malerelation>Father</malerelation>';
$retVal.='<malerelation>Father-in-law</malerelation>';
$retVal.='<malerelation>Grandfather</malerelation>';
$retVal.='<malerelation>Grandson</malerelation>';
$retVal.='<malerelation>Husband</malerelation>';
$retVal.='<malerelation>Nephew</malerelation>';
$retVal.='<malerelation>Son</malerelation>';
$retVal.='<malerelation>Son-in-law</malerelation>';
$retVal.='<malerelation>Uncle</malerelation>';
$retVal.='<malerelation>Other</malerelation>';

$retVal.='<femalerelation>Select..</femalerelation>';
$retVal.='<femalerelation>Aunt</femalerelation>';
$retVal.='<femalerelation>Cousin</femalerelation>';
$retVal.='<femalerelation>Daughter</femalerelation>';
$retVal.='<femalerelation>Daughter-in-law</femalerelation>';
$retVal.='<femalerelation>Granddaughter</femalerelation>';
$retVal.='<femalerelation>Grandmother</femalerelation>';
$retVal.='<femalerelation>Mother</femalerelation>';
$retVal.='<femalerelation>Mother-in-law</femalerelation>';
$retVal.='<femalerelation>Niece</femalerelation>';
$retVal.='<femalerelation>Sister</femalerelation>';
$retVal.='<femalerelation>Sister-in-law</femalerelation>';
$retVal.='<femalerelation>Wife</femalerelation>';
$retVal.='<femalerelation>Other</femalerelation>';

$retVal.='<nexttokin>No</nexttokin>';
$retVal.='<nexttokin>Yes</nexttokin>';
$retVal.='<maritalstatus>Select..</maritalstatus>';
$retVal.='<maritalstatus>Single</maritalstatus>';
$retVal.='<maritalstatus>Married</maritalstatus>';
$retVal.='<maritalstatus>Separated</maritalstatus>';
$retVal.='<maritalstatus>Widowed</maritalstatus>';
$retVal.='<maritalstatus>Divorced</maritalstatus>';
$retVal.='<sharedphone>No</sharedphone>';
$retVal.='<sharedphone>Yes</sharedphone>';

$retVal.='<faxphone>No</faxphone>';
$retVal.='<faxphone>Yes</faxphone>';
$retVal.='<mobilephone>No</mobilephone>';
$retVal.='<mobilephone>Yes</mobilephone>';

$retVal.='<visastatus>Select..</visastatus>';
$retVal.='<visastatus>App</visastatus>';
$retVal.='<visastatus>Received</visastatus>';
$retVal.='<visatype>Select..</visatype>';
$retVal.='<visatype>Official</visatype>';
$retVal.='<visatype>Tourist</visatype>';
$retVal.='<visatype>Business</visatype>';
$retVal.='<visatype>Study</visatype>';
$retVal.='<visasubtype>Select..</visasubtype>';
$retVal.='<visasubtype>Extension</visasubtype>';
$retVal.='<visasubtype>Entry</visasubtype>';

$retVal.='<qualification>None</qualification>';
$retVal.='<qualification>Technical</qualification>';
$retVal.='<qualification>Primary</qualification>';
$retVal.='<qualification>Lower Secondary</qualification>';
$retVal.='<qualification>Higher Secondary</qualification>';
$retVal.='<qualification>Under S.L.C.</qualification>';
$retVal.='<qualification>S.L.C.</qualification>';
$retVal.='<qualification>Certificate</qualification>';
$retVal.='<qualification>Intermediate</qualification>';
$retVal.='<qualification>Diploma</qualification>';
$retVal.='<qualification>Post Graduate Dip</qualification>';
$retVal.='<qualification>Bachelors</qualification>';
$retVal.='<qualification>Masters</qualification>';
$retVal.='<qualification>PhD</qualification>';

$retVal.='<workingWeek>5</workingWeek>';
$retVal.='<workingWeek>6</workingWeek>';
$retVal.='<treatmentsuccess>Yes</treatmentsuccess>';
$retVal.='<treatmentsuccess>No</treatmentsuccess>';
$retVal.='<treatmentcasepositive>Yes</treatmentcasepositive>';
$retVal.='<treatmentcasepositive>No</treatmentcasepositive>';
$retVal.='<treatmentreasonmain>Yes</treatmentreasonmain>';
$retVal.='<treatmentreasonmain>No</treatmentreasonmain>';
$retVal.='<treatmentreasontype>Both</treatmentreasontype>';
$retVal.='<treatmentreasontype>Inpatient</treatmentreasontype>';
$retVal.='<treatmentreasontype>Outpatient</treatmentreasontype>';
$retVal.='<patientbillpaidby>Self</patientbillpaidby>';
$retVal.='<patientbillpaidby>Donor</patientbillpaidby>';

$retVal.='<patientPAL>No</patientPAL>';
$retVal.='<patientPAL>Yes</patientPAL>';

$retVal.='<patientPWD>No</patientPWD>';
$retVal.='<patientPWD>Yes</patientPWD>';
$retVal.='<patientCAC>No</patientCAC>';
$retVal.='<patientCAC>Yes</patientCAC>';
$retVal.='<patientfootwearneeded>No</patientfootwearneeded>';
$retVal.='<patientfootwearneeded>Yes</patientfootwearneeded>';

$retVal.='<patientdischargedto>None</patientdischargedto>';
$retVal.='<patientdischargedto>Home</patientdischargedto>';
$retVal.='<patientdischargedto>Self-care</patientdischargedto>';
$retVal.='<patientdischargedto>Other Hospital</patientdischargedto>';
$retVal.='<patientdischargedto>Died</patientdischargedto>';
$retVal.='<patientaffected>Self</patientaffected>';
$retVal.='<patientaffected>Relative</patientaffected>';

$retVal.='<patientvisittype>Inpatient</patientvisittype>';
$retVal.='<patientvisittype>Outpatient</patientvisittype>';
$retVal.='<patientvisittype>Self-care</patientvisittype>';
$retVal.='<patientvisittype>Field</patientvisittype>';

$retVal.='</loadtypes>';

print $retVal;

/*JUST FOR TESTING PURPOSE*/
/*
$fh = fopen('loadtypetest.txt', "a"); 
fwrite($fh, $retVal); 
fwrite($fh,"\n");
fclose($fh); 
*/	

?>
